name: magic_workout_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_test:
    sdk: flutter
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  uuid: ^4.5.1
  mocktail: ^0.2.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  build_runner: ^2.4.13

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
